apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-nginx
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.25.0
          args:
            - /nginx-ingress-controller
            - --default-backend-service=default/api-poi-node-port-service
            - --annotations-prefix=nginx.ingress.kubernetes.io
          env:
            - name: POD_NAME
              value: api-ingress
              # valueFrom:
              #   configMapKeyRef:
              #     name: api-poi-config
              #     key: POD_NAME
                #fieldRef:
                  #fieldPath: metadata.name
            - name: POD_NAMESPACE
              value: default
              # valueFrom:
              #   configMapKeyRef:
              #     name: api-poi-config
              #     key: POD_NAMESPACE
                #fieldRef:
                  #fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
