apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: auth-sjcita-node-port-service
spec:
  ports:
      # service port in cluster
    - port: 3011
      # port to contact inside container
      targetPort: 3011
  selector:
    app: auth-sjcita
  type: NodePort
