apiVersion: v1
kind: ConfigMap
metadata:
  name: user-sjcita-config
  namespace: default
data:
  # SERVICE_NAME.NAMESPACE.svc.cluster.local:SERVICE_PORT
  MONGODB_CONNSTRING: mongodb://admin:admin@sjcita-mongo-cluster-ip-service.default.svc.cluster.local:27017
  AUTH_URL: auth-sjcita-node-port-service.default.svc.cluster.local:3011
